# Exercise 0
### Very Short PyTorch Intro (Skeleton)

## 0) Setup
- Import `torch`
- Import `numpy`
- Print the PyTorch version

In [4]:
# TODO
import torch
import numpy
print(torch.__version__)

2.12.0.dev20260407+cu128


## 1) Create Tensors
- Create `a` from the Python list `[1, 2, 3]`
- Create `b` as a `(2, 3)` tensor of ones
- Print `a` and `b`
- Print `a.shape` and `b.shape` so you can verify dimensions

In [7]:
# TODO
import torch
a = torch.tensor([1, 2, 3])
b = torch.ones(2, 3)
print(a)
print(b)
print(a.shape)
print(b.shape)

tensor([1, 2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3])
torch.Size([2, 3])


## 2) Basic Operations
- Create `x = [1.0, 2.0, 3.0]` and `y = [4.0, 5.0, 6.0]` as float tensors
- Compute element-wise addition
- Compute element-wise multiplication
- Store both results in variables and print them

In [11]:
# TODO
x = torch.tensor([[1.0, 2.0, 3.0]])
y = torch.tensor([[4.0, 5.0, 6.0]])

x_plus_y = x + y
x_times_y = x*y

print(x_plus_y)
print(x_times_y)

tensor([[5., 7., 9.]])
tensor([[ 4., 10., 18.]])


## 3) Convert Between NumPy and Torch
- Create a NumPy array: `np.array([10, 20, 30])`
- Convert it to a torch tensor
- Convert that tensor back to NumPy
- Print all three objects and their Python types to compare

In [4]:
# TODO
import numpy as np
import torch
np_array_orig = np.array([10,20,30])
torch_tensor = torch.from_numpy(np_array_orig)
np_array_new = torch_tensor.numpy()
print(f"Numpy orig: {np_array_orig} Type: {type(np_array_orig)}")
print(f"Torch tensor: {torch_tensor} Type: {type(torch_tensor)}")
print(f"Numpy new: {np_array_new} Type: {type(np_array_new)}")



Numpy orig: [10 20 30] Type: <class 'numpy.ndarray'>
Torch tensor: tensor([10, 20, 30]) Type: <class 'torch.Tensor'>
Numpy new: [10 20 30] Type: <class 'numpy.ndarray'>


## 4) Reshape
- Create a 1D tensor `t = torch.arange(12)`
- Reshape it to `(3, 4)`
- Reshape it back to `(12,)`
- Print the tensor values and all intermediate shapes

In [9]:
# TODO
t = torch.arange(12)
t_D2 = t.reshape(3,4 )
t_D1 = t_D2.reshape(12)
print(f"t: {t}, Shape: {t.shape}")
print(f"t_D2: {t_D2}, Shape: {t_D2.shape}")
print(f"t_D1: {t_D1}, Shape: {t_D1.shape}")

t: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), Shape: torch.Size([12])
t_D2: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), Shape: torch.Size([3, 4])
t_D1: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), Shape: torch.Size([12])


## 5) Permute Dimensions
- Create `img = torch.rand(3, 4, 5)` and treat dimensions as `(C, H, W)`
- Permute dimensions to `(H, W, C)` with `permute(...)`
- Print original and permuted shapes
- Optional check: print one element index before/after to see only axes changed, not values

In [11]:
# TODO
img_chw = torch.rand(3, 4, 5)
img_hwc = img_chw.permute(1, 2 ,0)
print(f"Img CHW: {img_chw}, Shape: {img_chw.shape}")
print(f"Img HWC: {img_hwc}, Shape: {img_hwc.shape}")

Img CHW: tensor([[[0.7026, 0.7901, 0.4602, 0.2005, 0.7484],
         [0.8483, 0.7568, 0.3123, 0.6627, 0.2997],
         [0.2885, 0.2324, 0.0760, 0.8024, 0.4728],
         [0.3801, 0.6747, 0.8487, 0.9445, 0.2509]],

        [[0.8556, 0.6910, 0.1113, 0.7154, 0.1598],
         [0.2774, 0.9715, 0.6852, 0.8346, 0.9624],
         [0.7945, 0.5452, 0.2503, 0.4076, 0.5990],
         [0.3806, 0.9890, 0.9195, 0.3224, 0.1668]],

        [[0.3358, 0.2767, 0.5140, 0.5427, 0.1069],
         [0.5350, 0.3984, 0.9945, 0.9652, 0.1103],
         [0.4660, 0.8724, 0.2927, 0.1338, 0.6431],
         [0.5110, 0.9628, 0.9143, 0.8506, 0.8664]]]), Shape: torch.Size([3, 4, 5])
Img HWC: tensor([[[0.7026, 0.8556, 0.3358],
         [0.7901, 0.6910, 0.2767],
         [0.4602, 0.1113, 0.5140],
         [0.2005, 0.7154, 0.5427],
         [0.7484, 0.1598, 0.1069]],

        [[0.8483, 0.2774, 0.5350],
         [0.7568, 0.9715, 0.3984],
         [0.3123, 0.6852, 0.9945],
         [0.6627, 0.8346, 0.9652],
         [0.2997,

## 6) Squeeze and Unsqueeze
- Create `z` with shape `(1, 3, 1, 5)` (you can use `torch.randn(...)`)
- Use `squeeze` to remove dimensions of size 1
- Use `unsqueeze` to add one dimension back at `dim=0`
- Print the shape after each step to track how rank changes

In [15]:
# TODO
z = torch.randn(1,3,1,5)
z_squeezed = z.squeeze()
z_unsqueezed = z_squeezed.unsqueeze(dim=0)

print(f"z: {z.shape}")
print(f"z_squeezed: {z_squeezed.shape}")
print(f"z_unsqueezed: {z_unsqueezed.shape}")

z: torch.Size([1, 3, 1, 5])
z_squeezed: torch.Size([3, 5])
z_unsqueezed: torch.Size([1, 3, 5])
